controller_list:
  - name: fake_centauri6dof_arm_controller
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
  - name: fake_centauri6dof_gripper_controller
    joints:
      - joint_gear1